inline_codeblock_color:
  default: --primary
  type: enum
  choices:
    - --primary
    - --tertiary
    - --quaternary
    - --danger
    - --success
inline_codeblock_weight:
  default: 500
  type: enum
  choices:
    - 500
    - 700
inline_codeblock_border_radius:
  default: 3px
  type: enum
  choices:
    - 0px
    - 3px
    - 5px
    - 10px